### ISSUE TITLE
Error after reconciliation of componentversion CR with artifactory repository 

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm-controller#104] opened 2023-02-03 06:55 UTC
Not able to fetch ocm component from artifactory docker repository 

Error logs:
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
1.6754061633892105e+09  INFO    ocm-component-version-reconcile starting ocm component loop     {"controller": "componentversion", "controllerGroup": "delivery.ocm.software", "controllerKind": "ComponentVersion", "ComponentVersion": {"name":"gardener-extension-provider-dns-infoblox","namespace":"ocm-system"}, "namespace": "ocm-system", "name": "gardener-extension-provider-dns-infoblox", "reconcileID": "c1fc53b7-500c-4b08-9efa-9c4ea3c4266e"}
1.675406163389273e+09   LEVEL(-4)       ocm-component-version-reconcile found component {"controller": "componentversion", "controllerGroup": "delivery.ocm.software", "controllerKind": "ComponentVersion", "ComponentVersion": {"name":"gardener-extension-provider-dns-infoblox","namespace":"ocm-system"}, "namespace": "ocm-system", "name": "gardener-extension-provider-dns-infoblox", "reconcileID": "c1fc53b7-500c-4b08-9efa-9c4ea3c4266e", "component": {"apiVersion": "delivery.ocm.software/v1alpha1", "kind": "ComponentVersion", "namespace": "ocm-system", "name": "gardener-extension-provider-dns-infoblox"}}
1.6754061633894248e+09  LEVEL(-4)       ocm-component-version-reconcile current reconciled version is   {"controller": "componentversion", "controllerGroup": "delivery.ocm.software", "controllerKind": "ComponentVersion", "ComponentVersion": {"name":"gardener-extension-provider-dns-infoblox","namespace":"ocm-system"}, "namespace": "ocm-system", "name": "gardener-extension-provider-dns-infoblox", "reconcileID": "c1fc53b7-500c-4b08-9efa-9c4ea3c4266e", "reconciled": "0.0.0"}
1.6754061653078496e+09  ERROR   Reconciler error        {"controller": "componentversion", "controllerGroup": "delivery.ocm.software", "controllerKind": "ComponentVersion", "ComponentVersion": {"name":"gardener-extension-provider-dns-infoblox","namespace":"ocm-system"}, "namespace": "ocm-system", "name": "gardener-extension-provider-dns-infoblox", "reconcileID": "c1fc53b7-500c-4b08-9efa-9c4ea3c4266e", "error": "failed to check version: failed to get latest component version: failed to get component versions: failed to list versions for component: failed to authorize: failed to fetch oauth token: unexpected status: 404 "}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234

**Comment by In-Ko** [comment] 2023-02-03 07:33
Have you tried to connect to the artifactory with e.g. postman ? If so, what was the result ? We need to rule out that this is something OCM controller specific, therefore I ask. Thanks!

**Comment by Skarlso** [comment] 2023-02-03 12:57
Could you please describe the steps to reproduce the problem?

**Comment by In-Ko** [comment] 2023-02-06 07:23
So the problem raised initially is more related to how one can get authorized towards the artifactory.

@Skarlso : One question remains: How would the ocm-controller then connects to the artifactory, using the mentioned "technical user", which mayank is going to request ?

**Comment by Skarlso** [comment] 2023-02-06 07:33
Using the appropriate docker pull secret.

**Comment by Skarlso** [comment] 2023-02-06 09:55
@mayankraipure12 Can you provide the component descriptor that this error produced? The issue is a bit different than the error message suggests. You shouldn't have access problems at that point. So we can figure out how you got there. :)

**Comment by ikhandamirov** [comment] 2023-02-17 13:18
Hi @mayankraipure12, does the problem still persist? Please update with the latest information. If it is resolved, please comment what the solution was and feel free to close the issue.

**Comment by mayankraipure12** [comment] 2023-03-17 05:06
Need to validate this issue

**Comment by Skarlso** [comment] 2023-04-12 07:47
I opt for closing this if this is no longer an issue.

**Comment by In-Ko** [comment] 2023-04-12 08:33
Same, so @mayankraipure12, please validate if the issue is solved or still occuring.

**Comment by mayankraipure12** [comment] 2023-04-12 08:59
I was able to pull the component from the artifactory and deploy it to the local cluster

**Closed** 2023-04-12 09:21 UTC
Labels: bug
